project:
  type: book
  output-dir: docs

book:
  title: "math-240-notes"
  author: "Katie St. Clair"
  date: "7/1/2024"
  reader-mode: true
  chapters:
    - index.qmd
    - first-principles.qmd
    - thinking-conditionally.qmd
    - intro-discrete-rv.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrbook



