# First principles of probability   {#sec-first-p}

First principles cover sections in chapter 1 of @dobrow. Make sure to review our [week 1 schedule](https://docs.google.com/spreadsheets/d/1QKQFfuuDzFUpOdjMvmHWZpR6zUzoxd9UjE83vA0H1Fs/edit?usp=sharing).

## Day 1 {.unnumbered}

- What to read: Read sections 1.1, 1.2, 1.3, 1.4, and 1.8 to see the generalization of property #3. 

- Learning objectives: These sections will help you
  - define basic probability and set theory terminology
  - define fundamental properties of probability
  

### Section 1.1 {.unnumbered}

Key terminology to know:

  - [ ] Sample space $\Omega$
  - [ ] Outcome $\omega$: this can also be called an <u>element</u>
  - [ ] Event $A$, $B$, ...

Comments: 

The sample space for a random experiment is the list of all possible outcomes. To define a sample space, start by thinking about how to define a couple individual outcomes and then generalize this to all outcomes. If there are a large or infinite number of outcomes, then you can use a "..." to show that a pattern will continue (like Examples 1.3 and 1.4).


There may not be a unique way to define a sample space and outcomes for a random experiment. For example, one may chose to define the sample space for Example 1.3 as just the number of votes for Yolanda $$\Omega = \{ 0, 1, 2, \dotsc, 999, 1000\}$$. But all the outcomes in a sample space must define unique possibilities for a random experiment (i.e. they are mutually exclusive, section 1.4).

"Complex" random experiments are often composed of simpler experiments. Example 1.2 is an example of this as we define one outcome for two dice rolls as the joint outcome of two individual die rolls. Similar for the sample space for three coin flips. In scenarios where the individual simpler experiments have equally likely outcomes, the outcomes in the more complex sample space (e.g. two dice rolls, three coin flips) are also equally likely outcomes. 


### Section 1.2-1.3 {.unnumbered}

Key ideas to know:

- [ ] relative frequency interpretation of probability
- [ ] probability function and its essential properties

Comments: 

Make sure you can put the probability function properties into words: (1) means probabilities can't be negative, (2) means something in the sample space has to happen with probability 1 and (3) means the probability of an event is just the sum of the probabilities of  outcomes that make up that event.



### Section 1.4 + 1.8 {.unnumbered}

Key <u>set theory</u> ideas to know

- [ ] complement $A^c$ (not $A$)
- [ ] union $A \cup B$ (at least one $A$ or $B$ or both)
- [ ] intersection $A \cap B = AB$ (both $A$ and $B$)
- [ ]  $(AB)^c = A^c \cup B^c$ (at most one)
- [ ] $(A \cup B)^c = A^cB^c$ (neither)
- [ ] $AB^c$ ($A$ but not $B$)
- [ ] subset $\subseteq$
- [ ] mutually exclusive/disjoint events
- [ ] Venn diagram
- [ ] empty set $\emptyset$


Comments: 

The first six ideas create a new event out of one or more events (think addition, subtraction, etc). Subset,  mutually exclusive and Venn diagrams tells us relational information about events (think less than, etc). The empty set is a set that has no outcomes (think zero).

Key <u>probability properties</u> to know

- [ ] Addition rule for mutually exclusive events (only add probability of events when they are mutually exclusive)
- [ ] General addition rule (events do not need to be mutually exclusive)
- [ ] Complement rule

Comments:

The addition rule properties are used to find the probability of a *union* of two or more events. When events are mutually exclusive, we just add the individual event probabilities. Make sure that you assess whether events are mutually exclusive before simply adding their probabilities. 

When events are not mutually exclusive, you start by adding event probabilities but then you need to subtract out the probability of the overlap (intersection) between events. The inclusion/exclusion rule is an extension of property (3) (eq. 1.3).

The complement rule along with the addition rule is useful for computing the probability of neither $A$ nor $B$: 
$$
P(A^c B^c) = 1 - P(A \cap B)
$$




## Day 2 {.unnumbered}

- What to read: Read sections 1.5 and 1.6

- Learning objectives: These sections will help you
  - use the multiplication principle to count the number of outcomes in a sample space or event
  - compute event probabilities using counting when outcomes are equally likely
  - define and count permutations

- Reading quiz: quiz 1

### Section 1.5 {.unnumbered}

Key idea to know:

- [ ] equally like outcomes 

Comments:

Our definition of the probability function Section 1.3 means that the probability of any event $A$ is equal to the number of outcomes in $A$ divided by the total number of outcomes when all outcomes are equally likely. 


### Section 1.6 {.unnumbered}

Key ideas to know:

- [ ] multiplication principle 
- [ ] permutation
- [ ] counting the number of permutations of $n$ unique/distinct objects
- [ ] counting the number of permutations of size $k$ from $n$ unique/distinct objects
- [ ] sampling with vs without replacement 

Comments: 

The outcomes counted by the multiplication principle describe a specific ordering, or arrangement, of a random experiment. For example 1.13, the outcomes in the sample space are found by fixing the exam (eg exams 1-4) and randomly assigning one of five grades to each exam. There are $5\times5\times5\times5 = 5^4$ such outcomes in the sample space. The complement of the event of interest is getting no A's and we must describe outcomes in this set the same way that we described them in the sample space (eg assigning one of four non-A grades to each exam). There are $4^4$ such ways to assign a non-A grade to each exam. 

Permutations are always ordered arrangements of unique/distinct objects or individual outcomes. 

Example 1.14 shows a common technique in counting problems. One outcome describes a specific (unique) arrangement of 15 books (eg positions 1-5 are top shelf, 6-10 middle, and 11-15 bottom). There are 15! such arrangements in the sample space. The event of interest, all math books on the bottom, uses both permutation counting and the multiplication principle. Permutations counts the number of ways to arrange math books (5!) and novels (10!). Each unique arrangement of math books can be combined with each unique arrangement of novels. Hence the multiplication principle is used to count the number of ways to get 10 novels on the top and middle shelves and 5 math books on the bottom: $10! \times 5!$. 

One twist to problem 1.14: suppose the event of interest was simply that the 5 math books were on the same shelf (ie they could be on the top, middle or bottom shelves). Each of these three options, $A_{top}, A_{middle}, A_{bottom}$ for math book placement has $10! \times 5!$ ways to arrange the books and each of these shelf positions $A_{i}$ is mutually exclusive. Hence the probability that the 5 math books are on the same shelf is found using the addition rule for mutually exclusive events:
$$
P(A_{top} \cup A_{middle} \cup A_{bottom}) = P(A_{top}) + P(A_{middle}) +  P(A_{bottom}) = 3 \times \dfrac{10! \times 5!}{15!}
$$


## Day 3 {.unnumbered}

- What to read: Read sections 1.7


- Learning objectives: These sections will help you
  - define and count combinations using the binomial coefficient
  - use the binomial coefficient to count permutations of two types of objects (a binary sequence)
  - distinguish between a permutation and a combination 

- Reading quiz: quiz 2


### Section 1.7 {.unnumbered}

Key ideas to know:

- [ ] combination
- [ ] correspondence between a binary sequence/list and an unordered subset/sample of size $k$ from $n$ unique objects
- [ ] binomial coefficient


Comments: 

We will be considering counting problems where outcomes are either *ordered* and *unordered*. Make sure that your strategy for solving a problem is consistent when counting sample space and event outcomes (eg don't use an ordered strategy for one and an unordered strategy for the other). 


While you need to describe outcomes in an event and sample space of interest in the same manner, you don't need to use the same counting method to count outcomes in each. e.g. Example 1.26 uses the multiplication principle to count all possible ways to flip a coin 20 times while the binomial coefficient is used to count how many of these outcomes contain example 10 H and 10 T. 

The binomial coefficient, which counts both the number of unordered subsets of unique objects and the number of binary sequences, can be generlized to a multinomial coefficient. Example 1.15(ii) involves picking 4 subsets of 13 cards from a deck of 52: $\frac{52!}{13!13!13!13!}$. Example 1.27(ii) also uses a multinomial coefficient in the numerator: $\frac{20!}{4!5!3!8!}$ counts the number of ways to arrange 4 As, 5 Gs, 3 Ts, and 8 Cs. 

Don't worry about the binomial theorem (and its proof) for now. 
