# Introduction to continuous random variables  {#sec-intro-cont-rv}

Chapter 6 of @dobrow introduces us to continuous random variables.

Make sure to review our [week 5 schedule](https://docs.google.com/spreadsheets/d/1p4s9FLap8CUB40UYAzdxpDi8-PkoHUceGq0dNUmfE9c/edit?usp=sharing).



## Day 13 {.unnumbered}

- What to read: Read intro to ch. 6, sections 6.1, 6.2, 6.4, 7.1.3

- Learning objectives: These sections will help you
  - understand what a continuous random variable is
  - use a probability mass function (pdf) to compute probabilities for events involving a continuous RV
  - use a cumulative distribution function (cdf) to compute probabilities for events involving a continuous RV
  - understand how to get a pdf from a cdf and vice versa
  - compute quantiles for a continuous distribution
  - get familiar with a (continuous) uniform RV
  
- After reading, take reading [quiz 6](https://forms.gle/gMDmvhPHPysXiPkK8)

  

### Section 6.1 {.unnumbered}

Key terminology to know:

  - [ ] continuous random variable
  - [ ] probability density function (pdf) of a continuous RV 

Comments: 

- Pay particular attention to the comment box on page 230. I am very particular when asking for pdf (or cdf) functions, especially on exams. If you are asked to define a pdf/cdf *over the entire real ine*, then you must get both the support $S$ and "0 otherwise" parts correct. 
- Yes, you will be integrating functions in this class! While I may ask you do to more involved calculations, eg integration by parts, on homework, I don't ask these longer calculation-focused questions on exams. Often (but not always) on exams, I'll ask you to appropriately "set-up" an integral but not actually complete the calculation.
- You can check integration calculations using technology, but you can't let technology do all the work. See the AI/tech homework policy on the syllabus. 



### Section 6.2 and 7.1.3 {.unnumbered}

Key terminology to know:

  - [ ] cumulative distribution function (cdf) of a continuous RV 
  - [ ] quantile of a continuous RV
  

Comments: 

- Take some time to make sure you see how pdf's and cdf's are related for continuous random variables.
- Take a look at the cdf example for a discrete RV, but I find cdf most useful for continuous RV. It is essential that you can use/derive cdf for continuous RV, but not as important for discrete (in my class).
- In 7.1.3, I just want you to review the definition of a quantile and how it relates to a cdf (6.2). You can skim the examples in 7.1.3, but we will formally introduce the normal distribution on another day.
- I've seen quantile described either as a percentage or a proportion/probability. E.g. the 50th quantile or the 0.5 quantile. Your book defines it as the former, "50th", but be comfortable with either description. 

### Section 6.4 {.unnumbered}

Key terminology to know:

  - [ ] uniform RV (know shorthand notation, basic properties)
  
Comments:

- You can just read up to Expectation and Variance on page 240. Review these after day 14's reading.
- Be comfortable computing probabilities for uniform RV using both a calculus approach and geometric approach. There are pros/cons to each, depending on the problem.



## Day 14 {.unnumbered}

- What to read: Read sections  6.3, 6.5, 7.1, 7.2, 7.4

- Learning objectives: These sections will help you
  - compute the expected value, variance and sd of a continuous RV
  - review important properties of expected values and variance/sd
  - get familiar with some common continous RV types (exponential, normal, gamma, beta)
  
- After reading, take reading [quiz 6](https://forms.gle/gMDmvhPHPysXiPkK8)

  

### Section 6.3 {.unnumbered}

Key terminology to know:

  - [ ] expected value of a continuous RV
  - [ ] variance/sd of a continuous RV
  

Comments: 

-  We'll cover 6.6-6.8 later this term



### Section 6.5 and 7.2 {.unnumbered}

Key terminology to know:

  - [ ] exponential RV (know shorthand notation, basic properties)
  - [ ] gamma RV (know shorthand notation, basic properties)
  - [ ] gamma function $\Gamma$
  

Comments: 

- Exponential and gamma are common models for "waiting times", eg time until something happens. 
- Make sure you recognize the exponential as a special case of the gamma
- We will cover the connection between these distributions and the Poisson distribution on another day


### Section  7.1 {.unnumbered}

Key terminology to know:

  - [ ] normal RV (know shorthand notation, basic properties)


Comments: 

- Skip 7.1.2 (pages 278-282)



### Section  7.4 {.unnumbered}

Key terminology to know:

  - [ ] beta RV (know shorthand notation, basic properties)


Comments: 

- The beta model is very useful for random variables that have a support between 0 and 1.


## Day 15 {.unnumbered}

- What to read: Read sections 8.1

- Learning objectives: This section will help you
  - use cdf's to derive the distribution (cdf, then pdf) of a function of a continuous RV
  
- No reading quiz on section 8.1

  

### Section 8.1 {.unnumbered}

Key terminology to know:

  - [ ] cdf and pdf (make sure these ideas are solid)
  

Comments: 

- Skim 8.1.1 and skip 8.1.2
- This section outlines how to derive the pdf of a function of a RV using the cdf method. 
- This method always "works", though often the mgf method is simpler *if* the function is linear and the pdf distribution is a common one (eg normal, exponential, etc). 
