# Introduction to discrete random variables  {#sec-intro-disc-rv}

Chapter 3 of @dobrow introduces us to discrete random variables and some common probability models used to describe these random variables. 

Make sure to review our [week 3 schedule](https://docs.google.com/spreadsheets/d/1u4l1ho1V35AJJSlt2-UaOW_C8xn46YK5UqrQjajpDH4/edit?usp=sharing).



## Day 7 {.unnumbered}

- What to read: Read sections 3.1, 3.2, 3.3, 3.4, plus the pmf definition on page 126

- Learning objectives: These sections will help you
  - understand what a "random variable" (RV) is
  - define a probability mass function and support set for a discrete RV
  - understand whether discrete RV are independent
  - get familiar with some common discrete RV types (uniform, Bernoulli, binomial, Poisson)
  
- After reading, take reading [quiz 6](https://forms.gle/bseg5bmmpyPQStLf8)

  

### Section 3.1 and page 126 {.unnumbered}

Key terminology to know:

  - [ ] random variable
  - [ ] discrete random variable
  - [ ] probability mass function (pmf) of a RV 
  - [ ] the (support) set $S$ of a RV
  - [ ] uniform RV (know shorthand notation, pmf and support set)
  

Comments: 

Pay special attention to the notation used for random variables (RV). Uppercase letters (typically at the end of the English alphabet) are used to denote the RV (which is random and doesn't have a fixed value) while lower case are used to denote a fixed numeric value (which is fixed even though there may not be a value specified).

The "distribution" of a random variable describes the probability structure of the RV, so think pmf if you are asked to describe a distribution. (ie what values of the RV are most likely, which ones are less likely, etc) You can also describe a distribution of a RV by name if it has a common pmf (eg "The distribution of $X$ is discrete uniform.")

The subsection "Random variables as function" explains how a RV $X(\cdot)$ takes in one or more outcomes $\omega$ from the sample space of an experiment and outputs a numeric value. This is our formal definition of a RV but we typically won't be using the $X(\omega)$ notation for a RV. Instead we will just refer to RV as $X$, $Y$, etc. But keep this underlying connection with the sample space in mind as the term progresses (especially for discrete RV).

The uniform random variable box on page 96 is an example of a probability mass function (pmf) and support set $S$. Even though pmf aren't formally defined until ch. 4, I find it useful to use that language at the start of discrete RV discussions. 


### Section 3.2 {.unnumbered}

Key terminology to know:

  - [ ] independent discrete random variables
  

Comments: 

We can use either Equations 3.1 or 3.2 to define two independent discrete RV. The general definition of independent random variables on page 98 extends beyond discrete RV to continuous RV (which we will cover soon). Skim this idea but our main focus right now is discrete RV. 


### Section 3.3 and 3.4 {.unnumbered}

Key terminology to know:

  - [ ] Bernoulli RV (know shorthand notation, what it counts, pmf and support set)
  - [ ] Independent and identically distributed (i.i.d.)
  - [ ] Binomial RV (know shorthand notation, what it counts, pmf and support set)


Comments: 

Bernoulli and binomial RV are extremely common types of RV so make sure to carefully review these sections. 

Your book describes a binomial RV as the sum of an [i.i.d.] Bernoulli "sequence" of length $n$. Another common way to describe this is the use the phrasing "trials" instead of "sequence": a binomial RV is the sum of $n$ i.i.d. Bernoulli trials.

The R code on pages 102 and 104 will be talked about on day 8.

Skim Example 3.14 but we will focus on solving problems involving two RV later on this term.



## Day 8 {.unnumbered}

- What to read: Read sections 3.5

- Learning objectives: These sections will help you
  - get familiar with the Poisson distribution
  - review or get introduced to infinite series 
  
- After reading, take reading [quiz 7](https://forms.gle/9dogqEKVC1WJoeR79)

  

### Section 3.5 {.unnumbered}

Key terminology to know:

  - [ ] Poisson RV (know shorthand notation, what it counts, pmf and support set)


Comments: 

A Poisson RV is another RV that counts "things", make sure you can distinguish settings where we should be modeling a count RV as a Poisson RV vs. a binomial RV (vs. something else). 

Series are a Calc BC or Math 210 topic that not all of you have seen. If you haven't had prior exposure to these ideas please stop by drop-in hours (or make an appointment) if you have questions! Appendix C at the end of your book reviews some useful math/calc facts, including some common series. You can use these facts without deriving them from scratch. 

Skim 3.5.1 and 3.5.2. Time permitting, I'll cover the proof connecting the binomial and Poisson distributions from 3.5.2 class (it's fun!) but it isn't essential course material.