# Some Limit Theorems {#sec-limit-thms}

We will explore strategies for deriving the distribution of a function of a two (or more) random variables. Then we return to thinking conditionally (first introduced in @sec-think-cond) to see how to define a conditional pdf/pmf probability model. 

Make sure to review our [week 8 schedule](https://docs.google.com/spreadsheets/d/1RrtZ7JiEBz_r4XMC7Eib2ObRZpGSXkg2fVV1h8YrnUw/edit?usp=sharing).



## Day 26 {.unnumbered}

- What to read: Read sections 10.5 and 10.6 but skip section 10.5.1

- Learning objectives: These sections will help you
  - understand and apply the Central Limit Theorem (CLT)
  - understand how the CLT is proven with MGF
  
- After reading, take reading [quiz 20](https://forms.gle/GK5weVcHN73WcQp8A)

  
### Sections 10.5 and 10.6 {.unnumbered}

Key terminology to know:

  - [ ] sum $S_n$ of $n$ i.i.d. random variables
  - [ ] mean $\bar{X}_n$ of $n$ i.i.d. random variables



Comments: 

- We will cover the proof of the CLT in 10.6 in class



## Day 27 {.unnumbered}

- What to read: Read sections 10.2 and 10.4

- Learning objectives: These sections will help you
  - understand the big picture implications of the Law of Large Numbers (LLN)
  - understand how Monte Carlo integration is an application of the LLN
  

  
### Sections 10.2 and 10.4 {.unnumbered}

Key terminology to know:

  - [ ] probability of a limit 
  - [ ] Monte Carlo integration

Comments: 

- Focus on the LLN big picture in 10.2
- We will use the LLN to justify an important application: Monte Carlo integration
